version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - python:3.8-slim
        - python:3.9-slim
        - python:3.10-slim
        - python:3.11-slim
        - python:3.12-slim
    command: nox
    volumes:
      - /tmp/.dragoman/.tox:/home/app/libs/.tox
      - /tmp/.pypoetry:/root/.cache/pypoetry
      - /tmp/.docker:/tmp/.docker
