countries = [
    {
        "app_label": "models",
        "model_name": "country",
        "pk": 1,
        "name": "Kazakhstan",
        "iso": "KZ",
        "iso3": "KAZ",
        "translate_fields": ["name"],
    },
    {
        "app_label": "models",
        "model_name": "country",
        "pk": 2,
        "name": "Thailand",
        "iso": "TH",
        "iso3": "THA",
        "translate_fields": ["name"],
    },
    {
        "app_label": "models",
        "model_name": "country",
        "pk": 3,
        "name": "Portugal",
        "iso": "PT",
        "iso3": "PRT",
        "translate_fields": ["name"],
    },
    {
        "app_label": "models",
        "model_name": "country",
        "pk": 4,
        "name": "Spain",
        "iso": "ES",
        "iso3": "ESP",
        "translate_fields": ["name"],
    },
    {
        "app_label": "models",
        "model_name": "country",
        "pk": 5,
        "name": "The Netherlands",
        "iso": "NL",
        "iso3": "NLD",
        "translate_fields": ["name"],
    },
]

translation = {
    "field://models/country/1/name": "Казахстан",
    "field://models/country/2/name": "Таиланд",
    "field://models/country/3/name": "Португалия",
    "field://models/country/4/name": "Испания",
    "field://models/country/5/name": "Нидерланды",
}
