# Generated by Django 4.2.9 on 2024-01-10 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCountry",
            fields=[
                ("name", models.CharField(help_text="Provide a name", max_length=255, verbose_name="Country name")),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_country_code",
                                message="Country code must be a 2 letter code",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                        verbose_name="Country code",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
    ]
